spring.application.name=resume-ai-backend

server.port=${PORT:8080}
server.address=0.0.0.0

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/resume_builder?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Vinit@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.secret=myVeryStrongSecretKeyForJwtAuthentication7765002708
jwt.expiration=86400000

# AI Configuration
spring.ai.model.chat=google-genai
spring.ai.google.genai.api-key=AIzaSyDJ8ple6XrPzBUnOhwz7aD0C_rvKsI0NJw
spring.ai.google.genai.chat.options.model=gemini-2.5-flash
spring.ai.google.genai.chat.options.temperature=0.4
